theme: jekyll-theme-minimal
title: Jade Henderson
logo: /profile/AD41C64B-58FF-4430-822A-C55955C14EEE.JPG
description: 
{% include spotifyalbum.html id="6AORtDjduMM3bupSWzbTSG?si=iQTumgiXRAiCYU7Oftk5SA" %}
