theme: jekyll-theme-minimal
title: Jade Henderson
logo: /profile/AD41C64B-58FF-4430-822A-C55955C14EEE.JPG
description: [A short description of your site's purpose]
layout: post
title: Your Title Here
spotifyplaylist: your playlist ID
{% include spotifyplaylist.html id=page.spotifyplaylist %}
