theme: jekyll-theme-minimal
title: Jade Henderson
logo: ![AD41C64B-58FF-4430-822A-C55955C14EEE](https://user-images.githubusercontent.com/69413123/111038515-6cc5df80-83f7-11eb-859f-9bcb70e936cd.JPG)
description: [A short description of your site's purpose]
